---
# Codacy configuration
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

exclude_paths:
  # Build outputs
  - "mcp/dist/**"
  - "**/node_modules/**"
  # Asset discovery files use dynamic paths for legitimate file operations
  # These are not path traversal vulnerabilities - paths come from controlled directory scanning
  - "mcp/src/services/file-discovery.ts"
  - "mcp/src/services/asset-loader.ts"
